# docker-compose.yml
version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_VERSION=v1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: ml_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
